### PR TITLE
haar cascade classifier for face detection

### PR DESCRIPTION
**Pull request by ghost**
added  haar cascade classifier for face detection

### CODE REVIEW

**Comment by andretimm** [comment]
@ashishkrishan1995  What this xml's ?

**Comment by ghost** [comment]
@andretimm xml's are the training files

**Comment by andretimm** [comment]
Do you can add this files ? @ashishkrishan1995

**Comment by ghost** [comment]
Yes adding

**Comment by ghost** [comment]
> Do you can add this files ? @ashishkrishan1995

@andretimm  added

**Pull request merged**
